[package]
authors = ["Lucas Brendel <lucasbrendel@gmail.com>"]
edition = "2018"
name = "green-thumb"
version = "0.1.0"

[dependencies]
chrono = "0.4.6"
log = "0.4.6"
rocket = "0.4.0"
rocket_codegen = "0.4.0-rc.1"
serde = "1.0.80"
serde_derive = "1.0.80"
# serde_rusqlite = "0.15.0"
simplelog = "0.5.3"
strum = "0.12.0"
strum_macros = "0.11.0"
diesel = { version = "1.3.3", features = ["postgres"] }
dotenv = "0.9.0"
diesel-derive-enum = { version = "0.4", features = ["postgres"] }

# [dependencies.rusqlite]
# features = ["chrono"]
# version = "0.15.0"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["handlebars_templates"]
