[package]
authors = ["Lucas Brendel <lucasbrendel@gmail.com>"]
edition = "2018"
name = "green-thumb"
version = "0.1.0"

[dependencies]
chrono = "0.4.7"
log = "0.4.6"
rocket = "0.4.1"
rocket_codegen = "0.4.2"
serde = "1.0.94"
serde_derive = "1.0.94"
# serde_rusqlite = "0.15.0"
simplelog = "0.6.0"
strum = "0.15.0"
strum_macros = "0.15.0"
diesel = { version = "1.4.2", features = ["postgres"] }
dotenv = "0.14.1"
diesel-derive-enum = { version = "0.4", features = ["postgres"] }

# [dependencies.rusqlite]
# features = ["chrono"]
# version = "0.15.0"

[dependencies.rocket_contrib]
version = "0.4.1"
default-features = false
features = ["handlebars_templates"]
