[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.flow]
dependencies = [
    "format",
    "clean",
    "build",
    "test"
]

[tasks.run]
env = { "ROCKET_CLI_COLORS" = "0" }
command = "cargo"
args = ["run"]

[tasks.migrate]
command = "diesel"
args = ["migration", "run"]

[tasks.migflow]
dependencies = [
    "migrate",
    "clean",
    "format",
    "build"
]