[tasks.format]
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.client-push]
script = [
 "cd client"
]

[tasks.client-release]
command = "cargo"
args = ["web", "--deploy", "--release"]

[tasks.client-flow]
dependencies = [
    "client-push",
    "format",
    "client-release"
]