(function() {var implementors = {};
implementors["green_thumb"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"green_thumb/schema/plants/struct.table.html\" title=\"struct green_thumb::schema::plants::table\">table</a>",synthetic:false,types:["green_thumb::schema::plants::table"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"green_thumb/schema/plants/columns/struct.star.html\" title=\"struct green_thumb::schema::plants::columns::star\">star</a>",synthetic:false,types:["green_thumb::schema::plants::columns::star"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"green_thumb/schema/plants/columns/struct.id.html\" title=\"struct green_thumb::schema::plants::columns::id\">id</a>",synthetic:false,types:["green_thumb::schema::plants::columns::id"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"green_thumb/schema/plants/columns/struct.title.html\" title=\"struct green_thumb::schema::plants::columns::title\">title</a>",synthetic:false,types:["green_thumb::schema::plants::columns::title"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"green_thumb/schema/plants/columns/struct.days_to_maturity.html\" title=\"struct green_thumb::schema::plants::columns::days_to_maturity\">days_to_maturity</a>",synthetic:false,types:["green_thumb::schema::plants::columns::days_to_maturity"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
